#ifndef DEFINES
#define DEFINES

#define BOARD_ID_NRF_BOARD    0 //ublox development kit
#define BOARD_ID_AWAN_WATCH   1 //Awan Watch

/*BLE ADMIN Commands Defined IDs*/
#define AW_ADMIN_CMD_TIME_SYNC    1
#define AW_ADMIN_CMD_MODE_CHANGE  2
#define AW_ADMIN_CMD_NOTIFICATION 3



//define MAX_NO_APPS     15
// #define INVALID_APP_ID  0xFF

/*Application Priorities*/
// #define HEARTRATE_APP_PRIORITY CONFIG_APPLICATION_INIT_PRIORITY + 1
// #define SPO2_APP_PRIORITY      CONFIG_APPLICATION_INIT_PRIORITY + 2
// #define ACC_APP_PRIORITY       CONFIG_APPLICATION_INIT_PRIORITY + 3
// #define TIMER_APP_PRIORITY     CONFIG_APPLICATION_INIT_PRIORITY + 4
// #define CALENDAR_APP_PRIORITY  CONFIG_APPLICATION_INIT_PRIORITY + 5

#endif /* DEFINES */
